### ISSUE TITLE
Remove Hard-coded 'Cancel' From ActionPanel

### ISSUE THREAD

**Issue by JoshuaKlaserAdslot** [Adslot/adslot-ui#1157]
In Symphony we have our own version of the ActionPanel that we use for modals. I want to replace this component with ActionPanel so that we don't have 2 component's doing the same thing.

We currently cannot use the ActionPanel as it contains the hard-coded English text 'Cancel' for the cancel button.

## Types of issue

- [ ] Bug (High impact or critical to a production build)
- [ ] Bug (Low impact or not working as expected)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Something else (idea, build tool, documentation improvement)

## Description
We were hoping to have the 'Cancel' text in the ActionPanel be replaced by a prop. It a business requirement that we have localised text in our new modals and the hard-coded English text means that we cannot use this. The prop can have a default value of 'Cancel' so that it doesn't cause breaking changes to make things easier.

**Comment by Harris-YWang** [comment]
Moved to the jira board. Close the issue
