### ISSUE TITLE
PropType of nodes.id required to be string

### ISSUE THREAD

**Issue by mdotwills** [Adslot/adslot-ui#462]
Just noticed in the PropTypes for the TreePicker in [L6](https://github.com/Adslot/adslot-ui/blob/master/src/helpers/propTypes/TreePickerPropTypes.js#L6), L11, L19, L26, we enforce the `id` as a string type. I find this a bit strange, given `id` is numerical and is coerced from the API as a number.

Leave it as a string, or accept numerical type too? (Only case for id being a string would be a uuid type id, which I don't think we use).

**Comment by omgaz** [comment]
ID, in this case is a reference *id*entifier. It could be a numerical id, a uuid or even a plain-text string to uniquely identify.

I get the confusion, but string does match all test cases accurately. We also don't want a custom prop-type or an `any` match on this.
