### ISSUE TITLE
Minimize dependency on lodash

### ISSUE THREAD

**Issue by Sutikshan** [Adslot/adslot-ui#601]
webpack bundle analyzer plugin is showing lodash being major portion of adslot-ui bundle.
Can we avoid using lodash methods and replace them with ES6 array function wherever we can.
and wherever we need any method, refer them specifically:

`import debounce from 'lodash/debounce';`

![image](https://user-images.githubusercontent.com/1274910/30309043-5a53058c-97cc-11e7-849a-4ff28da8ae54.png)

**Comment by nutboltu** [comment]
+1

**Comment by lightbringer1991** [comment]
or we can use this babel plugin to reduce the dist size without changing the code
https://github.com/lodash/babel-plugin-lodash

**Comment by omgaz** [comment]
It's not bundled as part of the dist as we use it heavily in adslot media/partner/publisher/api.

In Adslot UI we're using the following:

```
assign
cloneDeep
debounce
defaults
every
filter
first
forEach
get
groupBy
has
includes
includes
isEmpty
isNil
isNumber
kebabCase
last
map
noop
omit
pick
remove
some
split
sumBy
throttle
```

I think quite a few of these could be replaced with native es6. I think so many of these are used because of an initial linter rule to prefer lodash methods over native.

**Comment by Sutikshan** [comment]
Thanks @lightbringer1991 we will try out your suggestion, and see how it goes.

**Comment by lightbringer1991** [comment]
@Sutikshan please let me know how it goes
I use this in one of my personal projects, and it seems to be working ok.

**Comment by Sutikshan** [comment]
@lightbringer1991 No Luck. Faced couple of issues.
- We have to run this plugin against packages inside node_modules
- and all packages inside node_modules are babel compile version, which uses `require ` to import module, and this plugin works only with `import` as mentioned in [limitations](https://github.com/lodash/babel-plugin-lodash#limitations)

**Comment by Sutikshan** [comment]
Is it possible to compile adslot-ui dist version using this plugin, then we will have slimmer compiled adslot-ui

**Comment by lightbringer1991** [comment]
@omgaz sounds like something we can do. What do you think?

**Comment by Sutikshan** [comment]
@omgaz should I start work on it, I will create a PR.

**Comment by Sutikshan** [comment]
Tried, but got stuck in number of below errors :-

> ERROR in ./components/alexandria/Totals/index.jsx
> Module build failed: SyntaxError: C:/_Dev/adslot-ui/src/components/alexandria/Totals/index.jsx: Lodash chain sequences are not supported by babel-plugin-lodash.
> Consider substituting chain sequences with composition patterns.
> See https://medium.com/making-internets/why-using-chain-is-a-mistake-9bc1f80d51ba
>

**Comment by omgaz** [comment]
Have you tried one function at a time. it seems we can remove map and assign.

in terms of the totals chain surely we can:

turn this:
```
    {_(toSum)
      .reject({ isHidden: true })
      .map((item, index) =>
        <GridRow short horizontalBorder={false} key={index}>
          <GridCell stretch>{item.label}</GridCell>
          <GridCell dts={`${_.kebabCase(item.label)}-value`}>{valueFormatter(item.value)}</GridCell>
        </GridRow>
      )
      .value()}
```

into this:

```
      {_.reject(toSum, { isHidden: true })
        .map((item, index) =>
          <GridRow short horizontalBorder={false} key={index}>
            <GridCell stretch>{item.label}</GridCell>
            <GridCell dts={`${_.kebabCase(item.label)}-value`}>{valueFormatter(item.value)}</GridCell>
          </GridRow>
        )
      }
```

because reject will return an array that we can call the native `map` method on?
