### ISSUE TITLE
Use css-modules

### ISSUE THREAD

**Issue by omgaz** [Adslot/adslot-ui#604]
> CSS is easy. It’s like riding a bike, which is on fire and the ground is on fire and everything is on fire because it is hell. ([@iamdevloper](https://twitter.com/iamdevloper/status/753716544949981184?ref_src=twsrc%5Etfw))

---

Look at https://github.com/albburtsev/bem-cn

---

Although we traditionally prefer SMACSS across our application it doesn't really work on a component level.

> SMACSS doesn’t really work for individual components. This is intentional by design. SMACSS looks at the bigger picture and gives you a guideline of how your entire app’s CSS should be structured

(read https://medium.com/@durhailay/smacss-bem-a-css-brew-for-react-8629da831e89)

#### TL;DR

> - Use SMACSS for your app’s core CSS/SASS structure
> - Use BEM for your components

**Comment by xiaofan2406** [comment]
@omgaz I am a bit confused with this task. So are we going to switch to css-modules? or refactor our css to enforce BEM or SMACSS

**Comment by nimishjha** [comment]
I just hope we don't start using https://github.com/albburtsev/bem-cn, it looks confusing as hell and would only add another layer of obfuscation.
