### ISSUE TITLE
Upgrade to React v16

### ISSUE THREAD

**Issue by omgaz** [Adslot/adslot-ui#615]
https://facebook.github.io/react/blog/2017/09/26/react-v16.0.html

https://blog.discordapp.com/lessons-from-migrating-a-large-codebase-to-react-16-e60e49102aa6

Also involves upgrading to Enzyme 3

**Comment by lightbringer1991** [comment]
DO NOT UPGRADE until `react-bootstrap` is fully integrated with React16
As far as I know, `Modal` component breaks in React 16
https://github.com/react-bootstrap/react-bootstrap/issues/2812

**Comment by omgaz** [comment]
Hmm, I thought I commented on this one already haha maybe I didn't push `Save`. Yea this one needs to have breaking changes documented. Changes that affect Adslot products and upgrade path clearly defined as well as details around benefits being implemented.

**Comment by lightbringer1991** [comment]
It looks like the issue for react-modal is resolved, solution is in the issue.
I did a quick search on google, there seems to be no error other than the modal issue above.

Maybe we can proceed with React16 upgrade, just need to make sure that there are no console error on the demos.
