### ISSUE TITLE
Allow running a single test file (disable all coverage, linting when doing so)

### ISSUE THREAD

**Issue by lightbringer1991** [Adslot/adslot-ui#620]
This would be great when developing/fixing components, as we only focus on that component test file only.

**Comment by omgaz** [comment]
Disagree with the single-test run disabling all coverage and linting. I'd see these as separate flags as in.

```
# For single test run
--file=MyComponent.spec.jsx

# Do not lint or check coverage
--no-verify
  alias: --n
```

With composition such as:

```
npm run test --file=MyComponent.spec.jsx --n
```
