### ISSUE TITLE
Breaking: Remove Flat Button from Adslot UI

### ISSUE THREAD

**Issue by omgaz** [Adslot/adslot-ui#624]
![screen shot 2017-10-06 at 10 20 44](https://user-images.githubusercontent.com/908155/31256843-a127c5a8-aa80-11e7-9f39-4ea9b505cbb3.png)

![buttons](https://user-images.githubusercontent.com/908155/31257162-b69a1b00-aa82-11e7-8755-9ef68d40b978.gif)

Adslot UI has a `flat` button style that was introduced a few months ago. This button is not part of the pattern where button borderless is preferred.

Flat buttons have a `className` of `btn-flat` attached.

This task is to remove the associated styles, example and support.

The supported button style should be tracked down in the Adslot product and applied directly as a custom class on the close button.

**Comment by nimishjha** [comment]
I've removed the example and style on branch remove-btn-flat. But there aren't any instances of **btn-flat** in the adslot-ui project, so it might already have been removed.
