### ISSUE TITLE
Information Box

### ISSUE THREAD

**Issue by omgaz** [Adslot/adslot-ui#633]
Create a new InformationBox component. Extract from adslot marketplace landing page component. Will be used in campaign dashboard and marketplace.

Component should accept an SVG icon href as a prop and children nodes.

The SVG is to be placed as a circle to the left.
The children formatted to the right.
The width should be 100% of the parent element so it can be used in Bootstrap grid system.

Empty component:
![screen shot 2017-10-10 at 15 26 54](https://user-images.githubusercontent.com/908155/31369381-c5c31280-adcf-11e7-8b6f-7596d293a182.png)

Standard 30px spacing-etalon padding on component.
Background $color-gray-lightest (new variable needed)
Border none
font color: $color-text-label

Configured example:
![screen shot 2017-10-10 at 15 27 06](https://user-images.githubusercontent.com/908155/31369380-c595fcd2-adcf-11e7-9ba3-9634b3f62dae.png)

**Comment by sharmajyo** [comment]
a prop 'title' of type string is also added for showing the title text.
