### ISSUE TITLE
Search Component searchOnEnterKey is unexpected behaviour

### ISSUE THREAD

**Issue by omgaz** [Adslot/adslot-ui#634]
`src/components/adslot-ui/Search/index.jsx`.

Discussed with UX team and this is confusing. I think it unintuitive for the behaviour of search to be divided into two behaviours. There is also no cue for the user to press enter so they could be left waiting for a search that will never happen.

I believe this feature was added to prevent too many un-necessary calls to the external APIs.

A preferred solution would be to only perform a search when the uses finishes typing.

Possibly, have a prop set a high debounce (e.g. 5 seconds) on the search function with disabled leading but enabled trailing. `_.debounce(props.onSearch, 5000, { leading: false, trailing: true })` This will mean that when the user stops typing we perform the search.

**Comment by omgaz** [comment]
@Maxmus1989 What was the use case for searchOnEnterKey

**Comment by veegandhi** [comment]
Closing in favour of #822
