### ISSUE TITLE
Component Library changes

### ISSUE THREAD

**Issue by ksonder** [Adslot/adslot-ui#675]
## Types of issue

- [ ] Bug (High impact or critical to a production build)
- [ ] Bug (Low impact or not working as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Something else (idea, build tool, documentation improvement)

## Description

A few changes/improvements needed in the Component Library

## Expected Behaviour and Accepted Behaviour

Should allow for improved readability

## Current Behaviour

There is a lot of information contained in the Component Library which needs to be easier to scan

## Possible Solution

See PDF

## Screenshots

[Component library changes.pdf](https://github.com/Adslot/adslot-ui/files/1569854/Component.library.changes.pdf)

**Comment by lightbringer1991** [comment]
@omgaz  this seems to be outdated, since the pdf doesn't have design notes in it.
