### ISSUE TITLE
Cannot build on Windows

### ISSUE THREAD

**Issue by omgaz** [Adslot/adslot-ui#696]
## Types of issue

- [ ] Bug (High impact or critical to a production build)
- [x] Bug (Low impact or not working as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Something else (idea, build tool, documentation improvement)

## Description

I think one of our dependencies is not supported on Windows. I'll try a re-build or my node environment as Windows is rife with node/npm complications and lack of support.

## Expected Behaviour and Accepted Behaviour

Due to a mixed bag of development environments we need to support Windows/Mac/Linux for development to ensure the continuation of our open source collaboration.

- [ ] Should install and run on Windows
- [ ] Should be able to run dist on Windows (optional)
- [ ] Should still work on Mac
- [ ] Should still work on Linux (optional)
- [ ] Should add notes to check Windows builds for regression

## Current Behaviour

```
> npm i
npm ERR! missing: xxxx
npm ERR! missing: xxxx
npm ERR! missing: xxxx
npm ERR! missing: xxxx
...

etc...
```

## Screenshots

![windows](https://user-images.githubusercontent.com/908155/36409178-23e85ffe-165e-11e8-8a19-4cf14b18b9b2.PNG)

**Comment by veegandhi** [comment]
Probably need to investigate if this is still an issue after webpack upgrade. 

@glenkurniawan-adslot can you help us verify this as your recently did a feature on library.

**Comment by omgaz** [comment]
Looks like it builds and starts, however quite a few errors.

```
Error with path "src\components\fastStatelessWrapper\index.jsx": Error: No suitable component definition found.
Error: No suitable component definition found.
    at parse (C:\Users\omgaz\git\adslot-ui\node_modules\react-docgen\dist\parse.js:66:13)
    at Object.defaultParse [as parse] (C:\Users\omgaz\git\adslot-ui\node_modules\react-docgen\dist\main.js:61:29)
    at parse (C:\Users\omgaz\git\adslot-ui\node_modules\react-docgen\bin\react-docgen.js:106:17)
    at C:\Users\omgaz\git\adslot-ui\node_modules\react-docgen\bin\react-docgen.js:145:28
    at C:\Users\omgaz\git\adslot-ui\node_modules\node-dir\lib\readfiles.js:110:34
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
```

and lots of errors in the console:

```
error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
```

and components such as `card` and `grid` seem to crash the library.

But at least it builds :)

It's looking great BTW!

**Comment by veegandhi** [comment]
@omgaz - Thanks for verifying. The errors you see during the startup are from the prop generation where we don't have a decent way to ignore multiple files where props are not needed. There is a followup task to clean up this. 

console errors  and application crash should definitely be investigated

**Comment by glenkurniawan-adslot** [comment]
I can build and test adslot-ui on windows 
![adslot-ui_windows](https://user-images.githubusercontent.com/57419508/124210979-bf0a4800-db2f-11eb-8c92-2036c74bd0af.jpg)
![adslot-ui_test_windows](https://user-images.githubusercontent.com/57419508/124211032-cdf0fa80-db2f-11eb-9dab-ccc95a0c31b9.jpg)
