### ISSUE TITLE
Create a Pagination component

### ISSUE THREAD

**Issue by omgaz** [Adslot/adslot-ui#697]
As of React Bootstrap [0.32](https://github.com/react-bootstrap/react-bootstrap/blob/master/CHANGELOG.md#v0320) the Pagination component has had a drastic refactor. This means we are unable to upgrade React Bootstrap without either releasing a breaking change into Adslot UI or to create a Pagination component internally.

## Types of issue

- [ ] Bug (High impact or critical to a production build)
- [ ] Bug (Low impact or not working as expected)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Something else (idea, build tool, documentation improvement)

## Description

To continue using React Bootstrap we need to export a pagination component

## Expected Behaviour and Accepted Behaviour

- [ ] Should provide a non-breaking upgrade path for the Pagination component
- [ ] Should mimic existing functionality

## Possible Solution

Create a new Pagination Component under `third-party/bootstrap/Pagination` that maps expected React Bootstrap Pagination v31 prop types to v32 components. Supporting existing functionality and behaviour.

**Comment by omgaz** [comment]
Anyone can work on this, whether or not they use my pr as a base

**Comment by lightbringer1991** [comment]
I think I can work on this one on Friday.

**Comment by lightbringer1991** [comment]
I feel like we can just release a breaking change and proceed to fix the old code, that way we don't have to maintain another component.

**Comment by omgaz** [comment]
It's less about defending against a breaking change but more about preserving existing behaviour as desired.

The issue comes with Bootstrap not supporting pagination business logic that we re-use. Without it, every instance of the pagination component would need to roll it's own. This proposal is to keep the removed business logic as a "meaningful default".

**Comment by lightbringer1991** [comment]
@omgaz I think I'm a bit confused now.

So the goal here is that we make our own `Pagination` component that behaves like the `0.31` Pagination, but internally it will use `0.32` Pagination syntax, is that correct?

So basically we don't support `0.32` syntax at all, and always use the `0.31` syntax.

**Comment by lightbringer1991** [comment]
@omgaz I have some thoughts...

We will have the third-party Pagination component and it will behave the same with what we're doing currently.

However, we also supply something like `Pagination.Bootstrap`, and it basically the same with the newest version of react-bootstrap one. (considering we use the new Pagination anyway, so there is no extra code here)

```jsx
// Third-party pagination
<Pagination 
  activePage={activePage}
  items={totalPages}
  next
  onSelect={selectedPage => this.setState({ activePage: selectedPage })}
  prev
/>

// react-bootstrap pagination
<Pagination.Bootstrap>
  <Pagination.Bootstrap.Prev />
  <Pagination.Bootstrap.Item onClick={...}>{1}</Pagination.Bootstrap.Item>
  <Pagination.Bootstrap.Item onClick={...}>{2}</Pagination.Bootstrap.Item>
  <Pagination.Bootstrap.Item onClick={...}>{3}</Pagination.Bootstrap.Item>
  <Pagination.Bootstrap.Item onClick={...}>{4}</Pagination.Bootstrap.Item>
  <Pagination.Bootstrap.Next />
</Pagination.Bootstrap>
```
