### ISSUE TITLE
Proposal: New checkbox component to replace iCheck dependency

### ISSUE THREAD

**Issue by ChaoLiangSuper** [Adslot/adslot-ui#700]
The iCheck lib is out of date and not been updated for months. So, we might need our own checkbox component.

## Types of issue
- [x] Replace existed component 
- [ ] Deprecate `react-icheck`

## Description

- Build a new checkbox component
- Remove the old dependency

![screen shot 2018-04-19 at 14 44 56](https://user-images.githubusercontent.com/908155/38971818-47452388-43e0-11e8-8291-2d456f33b601.png)

**Comment by lightbringer1991** [comment]
if it is not so much different than iCheck, we can fork the library and maintain it ourselves (e.g. fixing bugs or implement new logic), without having to reinvent the wheel.

**Comment by ChaoLiangSuper** [comment]
@lightbringer1991 Sorry for the late update, I didn't get the notification for your comment 😂. I think to redo the icheck component because we can also reduce the size of our project. For instance, those themes in icheck we don't need them.

**Comment by omgaz** [comment]
Should try to support a painless migration from iCheck.
Should support radio and checkbox (returning a single value).
Should support radio and checkbox groups (returning an array or key/values).
Should support labels.
Should support disabled state.
Shouldn't support themes or style customisations.


Follow-up PR:
 - Should support NEW functionality of a tri-state.

**Comment by ChaoLiangSuper** [comment]
PR got merged. Closing this issue.

**Comment by omgaz** [comment]
This issue is not yet resolved, the radios have not yet been implemented as part of this issue - it's only halfway there.

**Comment by lightbringer1991** [comment]
if @nimishjha is busy with something else, I can give it a try on Radio buttons.

**Comment by lightbringer1991** [comment]
reopen since icheck has not been removed yet.

**Comment by ChaoLiangSuper** [comment]
Closing this issue and open another issue for removing the iCheck lib.
https://github.com/Adslot/adslot-ui/issues/727
