### ISSUE TITLE
References to React Bootstrap documentation is broken

### ISSUE THREAD

**Issue by lightbringer1991** [Adslot/adslot-ui#714]
React Bootstrap documentation page has been changed to a different structure, so our current reference urls no longer work.
e.g.
```
// old
https://react-bootstrap.github.io/components.html#buttons

// new
https://react-bootstrap.github.io/components/buttons/
```

## Types of issue

- [ ] Bug (High impact or critical to a production build)
- [ ] Bug (Low impact or not working as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Something else (idea, build tool, documentation improvement)

## Description
As per summary

## Expected Behaviour and Accepted Behaviour
N/A

## Current Behaviour
N/A

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
N/A

## Context
N/A

## Screenshots
N/A

**Comment by ChaoLiangSuper** [comment]
Closing... Issue fixed
