### ISSUE TITLE
Merge checkbox and radio into one component

### ISSUE THREAD

**Issue by ChaoLiangSuper** [Adslot/adslot-ui#736]
## Types of issue

- [ ] Bug (High impact or critical to a production build)
- [ ] Bug (Low impact or not working as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Something else (Clean up Code)

## Description

The checkbox and radio currently have 80% of code are same. 
So this two should be merge together without any effects.

**Comment by veegandhi** [comment]
Closing in favour of #809
