### ISSUE TITLE
Make Accordion component to have a max number of current open tab

### ISSUE THREAD

**Issue by ChaoLiangSuper** [Adslot/adslot-ui#799]
Make accordion component to have a max number of current open tabs when managing state.

for example 
In accordion (max open tab = 3) component state, it has [1, 2, 3] means the tab with id 1, 2, 3 is open 
Then click tab 4, the state will be [2, 3, 4], it will automatically close the first open tab. 

## Types of issue

- [ ] Bug (High impact or critical to a production build)
- [ ] Bug (Low impact or not working as expected)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Something else (idea, build tool, documentation improvement)

## Expected Behaviour and Accepted Behaviour

- [ ] Should …
- [ ] Should …
- [ ] Should …

## Steps to Reproduce (for bugs)

1.
1.
1.
1.

**Comment by veegandhi** [comment]
@ChaoLiangSuper - Why do we need to specify a number? as far as the accordion is allowed multi expand, the user can control the max tabs open?

**Comment by ChaoLiangSuper** [comment]
If we want the `accordion` to be uncontrolled. We can let it to control it. And there is no need to add extra codes to control it outside.

Also you can set which one is open by default.

**Comment by veegandhi** [comment]
I think it should be uncontrolled IMO.
