### ISSUE TITLE
A non-disappear popover

### ISSUE THREAD

**Issue by ChaoLiangSuper** [Adslot/adslot-ui#814]
Per requirement: 
Need a popover which can be triggered to show by clicking on it, and when the mouse is away it will not disappear. So the popover will stay there, and if the popover has some link in it, the link should be clickable as well.

**Comment by veegandhi** [comment]
Wondering if this whole thing can just be a Popover instead of thinking it as an controlled or uncontrolled? Supported props looks like
- Placement: left, right etc
- Theme
- Trigger: focus, click, alwaysShow ??

**Comment by veegandhi** [comment]
```
<Popover popoverContent={<div>content</div>} trigger="hover" placement="foo" theme="dark" >
   <cell>
</Popover>
```
