### ISSUE TITLE
React bootstrap, the way forward? 

### ISSUE THREAD

**Issue by veegandhi** [Adslot/adslot-ui#820]
## Types of issue

- [ ] Bug (High impact or critical to a production build)
- [ ] Bug (Low impact or not working as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Something else (idea, build tool, documentation improvement)

## Description

Seems that react bootstrap has not been upgraded due to breaking dependencies, we probably need to think a way forward with this. Possible solutions are: 
- To deprecate and decide the plan of action for following components:
```
Overlay
Button
Modal
Nav
Pagination
OverlayTrigger
Popover
```

- To upgrade and fix the breaking dependencies, so far to my knowledge:
```
Pagination
```

**Comment by lightbringer1991** [comment]
these are third party library warnings. We have already removed the deprecated lifecycle methods.
I think this will be resolves once we update react-bootstrap

**Comment by veegandhi** [comment]
@lightbringer1991 - Thanks for the info, I may convert this issue as a placeholder to map what we can do with React bootstrap moving forward

**Comment by veegandhi** [comment]
All we are left with now is `Button` and `Nav` in master project. This should be now a gtg.
