### ISSUE TITLE
Merge Search and Search Bar

### ISSUE THREAD

**Issue by veegandhi** [Adslot/adslot-ui#822]
## Types of issue

- [ ] Bug (High impact or critical to a production build)
- [ ] Bug (Low impact or not working as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Something else (idea, build tool, documentation improvement)

## Description
It looks like `Search` and `SearchBar` has a lot of similarities and `SearchBar` is more enhanced version of `Search`. 

This could be simplified to single component. From recent usage it seems that we need to revisit the logic in `Search` component this could be a good opportunity to execute this cleanup task.

**Comment by lightbringer1991** [comment]
@veegandhi so after some investigation on both component, I have a proposal for the workflow of the new Search component as follows:
- As loaded, displays an input field with Search icon
![Screen Shot 2019-04-05 at 11 44 47 am](https://user-images.githubusercontent.com/2588669/55597231-3ce81900-5798-11e9-9c41-98a7dbea7683.png)
- Upon entering search terms, we should allow both `searchOnKeyPress` and `searchOnEnter`
- Upon searching is triggered, the Search icon changes to Loading icon
- Upon searching is finished, the Loading icon is switched back the the Search icon.
- Allows controlled input through props, and trigger `onChange` if input is changed
- Proposed props and state
```jsx
static propTypes = {
  className: PropTypes.string,
  disabled: PropTypes.bool,
  placeholder: PropTypes.string,
  searchString: PropTypes.string,
  onChange: PropTypes.func,
  dts: PropTypes.string,
  searchType: PropTypes.array(['onEnter', 'onKeyPress']),
}

state = {
  isLoading: false,
  searchString: '',
};
```

**Comment by veegandhi** [comment]
@lightbringer1991 - Had a discussion in the review and considering all the scenarios the potential solution for the api was: 
```jsx
<Search
  value={this.state.value} // optional, overrides internal value management
  onChange={this.onChange} // optional until value is provided, need warning if not provided
  onSearch={this.onSearch} //  required
  debounceInterval={350} // optional 
  isLoading={this.state.isLoading} // optional, overrides internal state
  placeholder="foo" // required
  onClose={this.onClose} // optional
  icons= { search: React.Node, loader: React.Node, close: React.node } // needs more discussion
/>
```

**Comment by superpower1** [comment]
The new Search component will be like this:
```
<Search
  className="search-bar" // optional, additional class added to search component
  value={this.state.value} // optional, overrides internal value management
  onChange={this.onChange} // optional until value is provided
  onSearch={this.onSearch} //  required
  debounceInterval={350} // optional 
  isLoading={this.state.isLoading} // optional
  placeholder="foo" // optional
  onClear={this.onClear} // optional, triggered when close button is clicked
  dts="bar" // optional
  icons={ search: React.Node, loader: React.Node, close: React.node } 
  disabled={false} // optional, disable the input 
  searchOnEnter={false} // default value is false and so onSearch() is triggered when input changes
/>
```
