### ISSUE TITLE
Merge SvgCircle & SvgSymbol

### ISSUE THREAD

**Issue by veegandhi** [Adslot/adslot-ui#832]
## Types of issue

- [ ] Bug (High impact or critical to a production build)
- [ ] Bug (Low impact or not working as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Something else (idea, build tool, documentation improvement)

## Description

Looks like the circle can only be a prop instead of a complete separate component.

**Comment by veegandhi** [comment]
When #833 is closed, `SvgSymbol` should optionally accept `icon` as prop in conjunction with `href`. To render the internal icons

**Comment by lightbringer1991** [comment]
the current `SvgSymbol` props are a bit peculiar.

Current
```jsx
classSuffixes: PropTypes.arrayOf(PropTypes.string), // basically turns into `svg-symbol-component-<x> svg-symbol-component-<y>` with classSuffixes = ['x', 'y']
```
available values are defined in css file, they are either the size or colour of the svg
available sizes: 16, 70, 200, 250
available colours: 'color-disabled', 'cyan-dark', 'gray', 'gray-darker', 'gray-light', 'green-dark', 'orange-dark', 'red'

Proposal of a new prop structure
```jsx
...
size: PropTypes.oneOf([16, 70, 200, 250]), // default to 16 as the existing logic
colour: PropTypes.oneOf(['color-disabled', 'cyan-dark', 'gray', 'gray-darker', 'gray-light', 'green-dark', 'orange-dark', 'red']),
...
```

Maybe the text for colour can be different.
