### ISSUE TITLE
No styles for components after installed

### ISSUE THREAD

**Issue by superpower1** [Adslot/adslot-ui#860]
## Types of issue

- [x] Bug (High impact or critical to a production build)
- [ ] Bug (Low impact or not working as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Something else (idea, build tool, documentation improvement)

## Description

After I created a new fresh react app and installed adslot-ui, I found no styles are applied to  components. 

## Expected Behaviour and Accepted Behaviour

Styles should be applied to components as they are in the demo

## Steps to Reproduce (for bugs)

1. Create a new react app
1. Install adslot-ui
1. Import components from adslot-ui and use them in the app

**Comment by veegandhi** [comment]
Probably need a replication of code via codepen etc.

**Comment by superpower1** [comment]
I've verified that styles are working fine after I import css file `adslot-ui/dist/adslot-ui-main.css`. Although it seems apparently to include styles when using it, I think it's better to have it written in the readme file in case people forget to do so.

**Comment by veegandhi** [comment]
Let use this card as a placeholder to update our readme to include `styles.css`. Marking this as gtg

**Comment by veegandhi** [comment]
Documentation has been updated to reflect this. Closing
