### ISSUE TITLE
Add dts to Tag component

### ISSUE THREAD

**Issue by superpower1** [Adslot/adslot-ui#873]
## Types of issue

- [ ] Bug (High impact or critical to a production build)
- [x] Bug (Low impact or not working as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Something else (idea, build tool, documentation improvement)

## Current Behaviour

Currently, dts is adding to Tag like this ```data-test-selector={`tag-${id}`}```.

## Possible Solution

Maybe use a separate prop for dts and allow user to pass in their preferred dts.

**Comment by veegandhi** [comment]
use `dts` as other components. Also, check other components if they have this implementation.
