### ISSUE TITLE
Vertical Navigation

### ISSUE THREAD

**Issue by lightbringer1991** [Adslot/adslot-ui#874]
With a business case, it is good if we have a new vertical navigation component that can expand/collapse on demand. (see screenshots)
Expanded:
![Screen Shot 2019-07-02 at 1 54 28 pm](https://user-images.githubusercontent.com/2588669/60481501-ed4eb600-9cd0-11e9-8e40-7f2674bbde4c.png)

Collapsed:
![Screen Shot 2019-07-02 at 1 54 09 pm](https://user-images.githubusercontent.com/2588669/60481502-ef187980-9cd0-11e9-9f47-fa612618d306.png)

## Types of issue

- [ ] Bug (High impact or critical to a production build)
- [ ] Bug (Low impact or not working as expected)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Something else (idea, build tool, documentation improvement)

## Expected Behaviour and Accepted Behaviour

- [ ] Should …
- [ ] Should …
- [ ] Should …

## Possible Solution

With the new structure, I woud like to propose something like this.
```jsx
<VerticalNavigation activeTabId="1" isCollapsed={false}>
   <MenuContainer>
     <MenuItem tabId="1" menuIcon={React.Node} statusIcon={React.Node}>Product Details</MenuItem>
     <MenuItem tabId="2">...</MenuItem>
     ...
   </MenuContainer>

   <ContentContainer>
     <ContentItem tabId="1">...</ContentItem>
     <ContentItem tabId="2">...</ContentItem>
     ...
   </ContentContainer>
 </VerticalNavigation>
```

## Steps to Reproduce (for bugs)

1.
1.
1.
1.

**Comment by veegandhi** [comment]
Post offline discussion, suggested API: 
```jsx
<VerticalNavigation isCollapsed={false} onClick={() => void}>
  <MenuItem onClick={() => void} content={({ isCollapsed }) => React.Node} isActive={boolean}>
    {this.props.children}
  </MenuItem>
  <MenuItem onClick content={({ isCollapsed }) => React.Node}>
    {this.props.children}
  </MenuItem>
</VertiacalNavigation>
```

General notes: 
- to throw warning when `isActive` is false on all `MenuItem` and set the first tab as active
