### ISSUE TITLE
New toggle switch required for buffer charting 

### ISSUE THREAD

**Issue by adityasabnis** [Adslot/adslot-ui#877]
## Types of issue
- [X] New feature (non-breaking change which adds functionality)

## Description
- Designs are still being worked on. However, we most likely will need this component
- Not sure about the colors yet. (design just has one yellow)

## Possible Solution
http://www.bootstraptoggle.com/

## Screenshots
![image](https://user-images.githubusercontent.com/3688957/60941500-c45aa080-a322-11e9-9dbb-c8876c111184.png)

**Comment by veegandhi** [comment]
Apparently this component needs a very minimal css and can be developed without third-party dependency. However, can be done later. Low priority
