### ISSUE TITLE
Action Panel - Action panel should not render as a Sibling

### ISSUE THREAD

**Issue by pphminions** [Adslot/adslot-ui#878]
## Types of issue

- [ ] Bug (High impact or critical to a production build)
- [x] Bug (Low impact or not working as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Something else (idea, build tool, documentation improvement)

## Description

The action panel will render as a sibling of the surrounded component. Instead it should render as a sibling of the `body`.
Because of this the action panel backdrop not covering all the background. 

## Expected Behaviour and Accepted Behaviour

- [ ] Should …
- [ ] Should …
- [ ] Should …

## Possible Solution

wrapping the action panel with a div with `role="dialog"` will resolve the issue. this will seperate the content from the rest of the webpage

## Steps to Reproduce (for bugs)

1.
1.
1.
1.

## Screenshots

![Screen Shot 2019-07-11 at 4 02 04 pm](https://user-images.githubusercontent.com/7802760/61025855-47e4c200-a3f5-11e9-8d4e-5316caafe5da.png)

**Comment by veegandhi** [comment]
Closing this as fixed by #880
