### ISSUE TITLE
TreePickerSimplePure component: breadcrumb root is hard coded to 'All'

### ISSUE THREAD

**Issue by devanshiAdslot** [Adslot/adslot-ui#882]
## Types of issue

- [ ] Bug (High impact or critical to a production build)
- [ ] Bug (Low impact or not working as expected)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Something else (idea, build tool, documentation improvement)

## Description
The root for the Breadcrumb hyperlinks of the TreePickerSimplePure component is hardcoded to 'All'. This should be programmable as Symphony uses different languages in which 'All' will need to be translated.

## Expected Behaviour and Accepted Behaviour
A property of the component should define what should appear instead of the hard coded 'All'.

## Current Behaviour
Hard coded 'All' appears and there is no way to customize the same.

## Possible Solution
There should be a property for the component 'BreadCrumbRootText', which accepts a string. This property should be passed down and replace the hard coded 'All'.

## Context
We have started using the tree picker on one of the most used areas of Symphony and so need to translate all the text on the page to the current culture of the user.

## Screenshots
![image](https://user-images.githubusercontent.com/39894821/61341255-f4f18b80-a888-11e9-9272-9abd7d7942db.png)

**Comment by veegandhi** [comment]
Refactor impact to just accept everything as `breadCrumbNodes` and leave it on use to define the parent is pretty big. So this will need to be executed in two parts, `Breadcrumb` will need to be extended to accept `rootNode` with default value of `{ id: 'all', label: 'All' }` and then `TreePicker` will need to be further extended to accept `rootNode`.
