### ISSUE TITLE
Missing dependency `moment`

### ISSUE THREAD

**Issue by superpower1** [Adslot/adslot-ui#897]
Cannot resolve dependency `moment`.

## Types of issue

- [x] Bug (High impact or critical to a production build)
- [ ] Bug (Low impact or not working as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Something else (idea, build tool, documentation improvement)

## Description

Steps to reproduce: 

1. Start a new project
2. Run `npm i adslot-ui` 
3. Run `npm start`
4. See error on the screenshot

This is resolved after I manually install moment by running `npm i moment`.

## Screenshots

<img width="786" alt="Screen Shot 2019-07-24 at 4 41 49 pm" src="https://user-images.githubusercontent.com/8103605/61771651-b97c3180-ae33-11e9-8c21-6c56d8dff404.png">

**Comment by lightbringer1991** [comment]
can you link an example repository please.

**Comment by veegandhi** [comment]
This is expected. Moment, lodash, react, react-dom, react-redux and redux are not bundled. They are specified as `externals` in webpack build. However, we should add them as peer dependencies so it will warn the user during install if the listed packages do not exist.

**Comment by veegandhi** [comment]
Keeping this open to add these as peer dependency.
