### ISSUE TITLE
[Discussion] Non-general props & className props

### ISSUE THREAD

**Issue by knilink** [Adslot/adslot-ui#901]
Some props are used internally for like testing purpose.
dst: https://github.com/Adslot/adslot-ui/pull/900#discussion_r313727010

className: https://github.com/Adslot/adslot-ui/pull/900#discussion_r313726064

## Types of issue

- [ ] Bug (High impact or critical to a production build)
- [ ] Bug (Low impact or not working as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Something else (idea, build tool, documentation improvement)

**Comment by veegandhi** [comment]
Within the library we intentionally restrict the props which can be passed through. Closing this per offline discussion.
