### ISSUE TITLE
ActionPanel style is broken if the title is too long

### ISSUE THREAD

**Issue by knilink** [Adslot/adslot-ui#904]
## Types of issue

- [ ] Bug (High impact or critical to a production build)
- [x] Bug (Low impact or not working as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Something else (idea, build tool, documentation improvement)

## Description

some user custom titles may be very long

## Screenshots

<img width="1023" alt="Screen Shot 2019-08-27 at 2 47 58 pm" src="https://user-images.githubusercontent.com/17878530/63741865-0c855080-c8da-11e9-8e87-db8474bc7e55.png">

**Comment by veegandhi** [comment]
Make the title overflow to `ellipsis`.
