### ISSUE TITLE
Adding a search box to selected items in tree picker

### ISSUE THREAD

**Issue by ozdenyilmazadslot** [Adslot/adslot-ui#906]
We need a second search box in the included items in the tree picker 

## Types of issue
 What types of issue are we looking at? Put an `x` in all the boxes that apply: 
- [ ] Bug (High impact or critical to a production build)
- [ ] Bug (Low impact or not working as expected)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Something else (idea, build tool, documentation improvement)

## Description
 We want to use the treepicker to give users access to clients & campaigns on paltform. When we showed the treepicker to user, they gave us feedback about the included clients/campaigns being too many and that being able to search in them would prove beneficial 

## Screenshots
We need the following search box :
![Screen Shot 2019-09-06 at 9 36 27 am](https://user-images.githubusercontent.com/54965045/64390878-e5711080-d089-11e9-92d5-725d69a83f1f.png)

**Comment by veegandhi** [comment]
Adding a new prop named `selectedSearch` which will accept `React.Node` to the `TreePickerSimplePureComponent`. The user will control the selected nodes externally. 

```jsx
selectedSearch: React.Node
```

As part of the this task, we will need to add a demo for a usage.
Example usage would look like:

```jsx
selectedNodes={this.filteredSelectedNodeList}
selectedSearch={<Search onSearch={selectedSearchValue => this.setState({ selectedSearchValue })} />}

```

**Comment by lightbringer1991** [comment]
we can actually put anything in the `selectedSearch` node, not necessarily a search bar.
I propose to change it to `selectedTopBar`, or something equivalent.

**Comment by veegandhi** [comment]
> we can actually put anything in the `selectedSearch` node, not necessarily a search bar.

I think this came up in discussion. There was also another discussion to check if it has adslot-ui Search box. But consensus was that there will be not much of a use case anything but search bar can be placed there apart as it will be a style fail for starters and if the user still chooses to put anything but search bar, no further support will be provided to maintain it.
