### ISSUE TITLE
Design changes to Switch component

### ISSUE THREAD

**Issue by adityasabnis** [Adslot/adslot-ui#930]
## Types of issue

- [ ] Bug (High impact or critical to a production build)
- [ ] Bug (Low impact or not working as expected)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Something else (idea, build tool, documentation improvement)

## Description

Change of design

#### Expected
![image](https://user-images.githubusercontent.com/3688957/66786255-7fe72e00-ef2b-11e9-9a65-9425b857591b.png)

#### Current
![image](https://user-images.githubusercontent.com/3688957/66786348-be7ce880-ef2b-11e9-821e-abd7814b8670.png)

**Comment by lightbringer1991** [comment]
wait what!!!!
design changes again?!
