### ISSUE TITLE
Improve AlertInput component

### ISSUE THREAD

**Issue by lightbringer1991** [Adslot/adslot-ui#957]
`AlertInput` structure seems to be more complicated comparing to what it should be.
Proposing a new DOM structure for the component (see attached PR)

## Types of issue

- [ ] Bug (High impact or critical to a production build)
- [ ] Bug (Low impact or not working as expected)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Something else (idea, build tool, documentation improvement)

**Comment by lightbringer1991** [comment]
@adityasabnis I heard that you wanted to make improvements on this component a while ago, maybe we can incorporate into this issue.

**Comment by veegandhi** [comment]
Looks like the improvements were individually done on the alert input do the cleanup pr should be gtg.
