### ISSUE TITLE
Implement typing for the library

### ISSUE THREAD

**Issue by lightbringer1991** [Adslot/adslot-ui#965]
Right now `adslot-ui` does not have a type file, which means we do not know the syntax of each components unless we open the demo when writing code.

By implementing a type file, it will be faster to implement the components.

## Types of issue

- [ ] Bug (High impact or critical to a production build)
- [ ] Bug (Low impact or not working as expected)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Something else (idea, build tool, documentation improvement)

**Comment by veegandhi** [comment]
Does look like a lot of manual work. However, if there is a way to automate it. This feature will be a lot of value.
