### ISSUE TITLE
TreePicker node requires dynamically changing color base on `node` data.

### ISSUE THREAD

**Issue by xiaofan2406** [Adslot/adslot-ui#980]
## Types of issue

- [ ] Bug (High impact or critical to a production build)
- [ ] Bug (Low impact or not working as expected)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Something else (idea, build tool, documentation improvement)

## Description

New design requires `TreePicker` node requires dynamically changing background color base on `node` data.

Some WIP proposal PR in https://github.com/Adslot/adslot-ui/pull/979, by injecting classname dynamically.

**Comment by veegandhi** [comment]
Per discussion, we probably need all standard colour accents that we use.

**Comment by veegandhi** [comment]
Add propert `accent` to Proptypes.node to accept all the colour statues from existing component.  Best example will be `Tag` component.
